# Generated by Django 3.1.2 on 2020-10-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter_address', models.CharField(max_length=126)),
                ('company', models.CharField(max_length=126)),
                ('leader', models.CharField(max_length=126)),
            ],
        ),
        migrations.CreateModel(
            name='Shelter_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
            ],
        ),
    ]
